#!/bin/bash

echo "📧 Email Configuration Setup Guide"
echo "=================================="
echo ""
echo "To enable 2FA email functionality, follow these steps:"
echo ""
echo "1. 🔐 Enable 2-Factor Authentication on your Gmail account:"
echo "   - Go to: https://myaccount.google.com/security"
echo "   - Enable 2-Step Verification"
echo ""
echo "2. 🔑 Generate an App Password:"
echo "   - Go to: https://myaccount.google.com/apppasswords"
echo "   - Select 'Mail' and your device"
echo "   - Copy the generated 16-character password"
echo ""
echo "3. ✏️ Update the .env file:"
echo "   - Replace 'mohamed.a.aboelnil@gmail.com' with your Gmail address"
echo "   - Replace '120120Asd#$##' with the App Password from step 2"
echo ""
echo "4. 🔄 Restart the server after updating .env"
echo ""
echo "💡 Alternative email providers:"
echo "   - Outlook/Hotmail: smtp-mail.outlook.com, port 587"
echo "   - Yahoo: smtp.mail.yahoo.com, port 587"
echo "   - Custom SMTP: Update EMAIL_HOST and EMAIL_PORT accordingly"
echo ""
echo "🧪 To test email configuration:"
echo "   cd backend && node test-email.js"
echo ""

read -p "Press Enter to continue..."